---
# Default values for the appformix_gcp_adapter role.  These can be
# overridden when including the role.
appformix_gcp_adapter_version: "{{ appformix_version }}"
appformix_gcp_adapter_state: "{{ appformix_state }}"
appformix_gcp_adapter_pull: "missing"
