---
# Delete cluster from multicluster dashboard with HAproxy

- include: host_translation.yml

- hosts: appformix_controller
  roles:
    - appformix_defaults
    - { role: appformix_master_auth, when: appformix_state != 'absent' }

- hosts: appformix_controller_master
  vars:
    auth_token: "{{ master_auth_token }}"
    auth_type: "appformix"
  roles:
    - appformix_defaults
    - { role: appformix_multicluster_config, cluster_config_action: 'delete',
        when: appformix_state != 'absent' }

- hosts: appformix_controller
  vars:
    cluster_id: "{{ hostvars[groups['appformix_controller_master'][0]]['deleted_cluster_id'] }}"
  roles:
    - appformix_defaults
    - { role: appformix_multicluster_haproxy, haproxy_action: 'delete'}
