---
# Install AppFormix components
#
# Arguments:
#   appformix_ssl_cert : path to SSL certificate file (optional)
#   appformix_ssl_key  : path to SSL private key file (optional)
#   appformix_license  : path to AppFormix license file (optional)
#
# To enable HTTPS protocol for REST APIs, pass an SSL certificate
# and private key as arguments when running this playbook (e.g.,
# "-e 'appformix_ssl_cert=...' -e 'appformix_ssl_key=...'")
#

- include: host_translation.yml

- hosts: appformix_controller_master:appformix_controller_worker
  tags: appformix_controller
  roles:
    - appformix_defaults
    - appformix_filesystem
    - { role: appformix_logrotate, when: appformix_state != 'absent' }
    - { role: appformix_certs, when: appformix_ssl_cert is defined and appformix_ssl_key is defined }
    - { role: appformix_network, when: appformix_state != 'absent' }
    - { role: appformix_docker_images, when: appformix_state != 'absent' }
    - { role: appformix_keepalived, when: (install_keepalived_flag|bool) == True }
    - { role: appformix_redis, appformix_redis_exposed_port: "{{ appformix_haproxy_redis_port }}" }

- include: appformix_mongo_cluster.yml

- hosts: appformix_controller_master:appformix_controller_worker
  sudo: yes
  roles:
    - { role: appformix_haproxy }

- hosts: appformix_controller_master:appformix_controller_worker
  tags: [ appformix_controller, appformix_upgrade ]
  roles:
    - appformix_defaults
    - appformix_translate

- hosts: appformix_controller_master:appformix_controller_worker
  tags: appformix_controller
  roles:
    - appformix_defaults
    - { role: appformix_license, when: appformix_license is defined }
    - appformix_datamanager
    - appformix_dashboard
    - { role: appformix_datamanager, datamanager_action: "configure" }

- hosts: appformix_controller_master:bare_host:ceph_osd:ceph_monitor:compute:openstack_controller:appformix_controller_worker
  tags: appformix_manager
  roles:
    - appformix_manager

- hosts: appformix_controller_master
  tags: [ appformix_nfx150_setup ]
  roles:
    - appformix_defaults
    - { role: appformix_nfx150_config,
        when: nfx150 | length > 0 }
