---
- name: Get VCenter Admin Token
  uri:
    url: "{{ auth_post_url }}"
    method: POST
    body: ' {"UserName": "{{ appformix_vcenter_adapter_vcenter_user  }}",
             "Password": "{{ appformix_vcenter_adapter_vcenter_password }}",
             "AuthType": "{{ appformix_vcenter_adapter_auth_type }}"} '
    HEADER_Content-Type: "application/json"
    validate_certs: no
  register: auth_info
  delegate_to: localhost

- name: Set fact for VCenter token
  set_fact:
    auth_info: "{{ auth_info }}"
