---
- name: Create tag for all AppFormix Controllers
  appformix_tag:
      token: "{{ auth_token }}"
      auth_type: "{{ auth_type }}"
      hosts: '{{ appformix_controllers }}'
      tag_name: '{{ appformix_controller_tag }}'
      post_url: '{{ aggregate_post_url }}'
      task_url: '{{ task_url }}'
  when: create_appformix_controller_tag

- name: Create tag for all Openstack Controllers
  appformix_tag:
      token: "{{ auth_token }}"
      auth_type: "{{ auth_type }}"
      hosts: '{{ openstack_controllers }}'
      tag_name: '{{ appformix_openstack_controller_tag }}'
      post_url: '{{ aggregate_post_url }}'
      task_url: '{{ task_url }}'
  when: create_openstack_controller_tag and openstack_controllers

- name: Create tag for all Ceph Monitors
  appformix_tag:
      token: "{{ auth_token }}"
      auth_type: "{{ auth_type }}"
      hosts: '{{ ceph_monitor }}'
      tag_name: '{{ appformix_ceph_monitor_tag }}'
      post_url: '{{ aggregate_post_url }}'
      task_url: '{{ task_url }}'
  when: create_ceph_monitor_tag and ceph_monitor

- name: Create tag for all Ceph Osds
  appformix_tag:
      token: "{{ auth_token }}"
      auth_type: "{{ auth_type }}"
      hosts: '{{ ceph_osd }}'
      tag_name: '{{ appformix_ceph_osd_tag }}'
      post_url: '{{ aggregate_post_url }}'
      task_url: '{{ task_url }}'
  when: create_ceph_osd_tag and ceph_osd

 - name: Create tag for all nfx150 Hosts
   appformix_tag:
      token: "{{ auth_token }}"
      auth_type: "{{ auth_type }}"
      hosts: '{{ nfx150 }}'
      tag_name: '{{ appformix_nfx150_tag }}'
      post_url: '{{ aggregate_post_url }}'
      task_url: '{{ task_url }}'
  when: appformix_nfx150_tag and nfx150
