---

- name: Get Kubernetes Admin Token
  uri:
    url: "{{ auth_post_url }}"
    method: POST
    body: ' {"UserName": "kubernetes",
             "Password": "kubernetes",
             "AuthType": "{{ kubernetes_auth_type }}"} '
    HEADER_Content-Type: "application/json"
    validate_certs: no
  register: auth_info
  delegate_to: localhost

- name: set fact for kubernetes token
  set_fact:
    auth_info: "{{ auth_info }}"
