---
appformix_mongo_configsrv_data_dir_container: "/data/db"
appformix_mongo_configsrv_script_dir_container: "/scripts"

# Constants defined for the appformix_mongo role.
# These should not be overridden.
appformix_mongo_configsrv_data_volume:
    - "{{ appformix_mongo_configsrv_data_dir }}:{{ appformix_mongo_configsrv_data_dir_container }}"
    - "{{ appformix_mongo_configsrv_script_dir }}:{{ appformix_mongo_configsrv_script_dir_container }}"
appformix_mongo_configsrv_volumes: "{{ appformix_mongo_configsrv_data_volume }}"

appformix_mongo_add_users_script: "add_mongodb_users.js"
