---
appformix_haproxy_dir_state: "{{ (appformix_haproxy_state == 'absent') | ternary('absent','directory') }}"
appformix_haproxy_cfg_file: "haproxy.cfg"
appformix_haproxy_volumes:
    - "{{ appformix_haproxy_host_config_dir }}:/usr/local/etc/haproxy"
    - "{{ appformix_haproxy_host_scripts_dir }}:/haproxy"
appformix_haproxy_socket_stat_file: "/usr/local/etc/haproxy/haproxy.sock"

appformix_haproxy_exposed_docker_ports_mapping:
    - "{{ appformix_multicluster_haproxy_stats_port }}:{{ appformix_multicluster_haproxy_stats_port }}"
    - "{{ multicluster_haproxy_port }}:{{ multicluster_haproxy_port }}"

appformix_haproxy_internal_docker_ports_list:
    - "{{ appformix_multicluster_haproxy_stats_port }}"
    - "{{ multicluster_haproxy_port }}"
