---
- name: Ensure haproxy script and config directories exist
  become: yes
  file:
      path: "{{ item }}"
      state: "{{ appformix_haproxy_dir_state }}"
      owner: root
      group: root
      mode: 0755
  with_items:
      - "{{ appformix_haproxy_host_config_dir }}"
      - "{{ appformix_haproxy_host_scripts_dir }}"
  when: is_master_cluster

- name: Copy HAProxy configuration file to the management host
  become: yes
  template:
      src: "{{ appformix_haproxy_cfg_file }}"
      dest: "{{ appformix_haproxy_host_config_dir }}"
      force: yes
      owner: root
      group: root
      mode: 0755
  when: appformix_haproxy_state != 'absent' and is_master_cluster

- name: Copy all required scripts to the management host
  become: yes
  template:
      src: "{{ item }}"
      dest: "{{ appformix_haproxy_host_scripts_dir }}"
      force: yes
      owner: root
      group: root
      mode: 0755
  with_items:
      - server_check_script.sh
  when: appformix_haproxy_state != 'absent' and is_master_cluster

- name: Start AppFormix HaProxy container
  docker:
      name: appformix-multicluster-haproxy
      image: "{{ appformix_haproxy_image }}"
      state: "{{ appformix_haproxy_state }}"
      restart_policy: always
      net: "{{ appformix_network }}"
      ports: "{{ appformix_haproxy_exposed_docker_ports_mapping }}"
      expose: "{{ appformix_haproxy_internal_docker_ports_list }}"
      volumes: "{{ appformix_haproxy_volumes }}"
      hostname: "haproxy_{{ ansible_hostname }}"
  when: appformix_haproxy_state != 'absent' and is_master_cluster and haproxy_action == 'add'

- name: Execute script to add required entries to HAProxy configuration file
  become: yes
  script: >
      add_entries_to_haproxy_conf.sh {{ cluster_id }} {{ multicluster_haproxy_port }} {{ appformix_haproxy_host_config_dir }} {{ appformix_haproxy_cfg_file }} {{ cluster_controller_host }} {{ cluster_controller_port }}
  when: appformix_haproxy_state != 'absent' and haproxy_action == 'add'

- name: Execute script to remove required entries from HAProxy configuration file
  become: yes
  script: >
      remove_entries_from_haproxy_conf.sh {{ cluster_id }}
          {{ appformix_haproxy_host_config_dir }} {{ appformix_haproxy_cfg_file }}
  when: appformix_haproxy_state != 'absent' and haproxy_action == 'delete'

- name: Reload HAProxy config through supervisorctl
  become: yes
  shell: docker exec appformix-multicluster-haproxy bash -c "supervisorctl signal HUP haproxy:*"
  when: appformix_haproxy_state != 'absent'

- name: Stop AppFormix HaProxy container
  docker:
      name: appformix-multicluster-haproxy
      image: "{{ appformix_haproxy_image }}"
      state: "absent"
      restart_policy: always
      net: "{{ appformix_network }}"
      ports: "{{ appformix_haproxy_exposed_docker_ports_mapping }}"
      expose: "{{ appformix_haproxy_internal_docker_ports_list }}"
      volumes: "{{ appformix_haproxy_volumes }}"
      hostname: "haproxy_{{ ansible_hostname }}"
  when: appformix_haproxy_state == 'absent' or (is_master_cluster and haproxy_action == 'delete')
