---
# Default values for the appformix_aws_adapter role.  These can be
# overridden when including the role.
appformix_aws_adapter_version: "{{ appformix_version }}"
appformix_aws_adapter_state: "{{ appformix_state }}"
appformix_aws_adapter_pull: 'missing'
