---
platform_setup_url: "{{ appformix_vip_url }}/appformix/v1.0/setup"

appformix_infrastructure_view_roles:
    - 'admin'

appformix_administrator_roles:
    - 'admin'

appformix_read_only_infrastructure_view_roles: []

# Ansible 1.9.6 looks for templates only in the current directory. Use relative path to
# specify location of the template file.
config_json: '{{ lookup("template", "../templates/config.json.j2") }}'
